### ISSUE TITLE
Add 'version' command

### ISSUE THREAD

**Issue by loksonarius** [UltimateSoftware/envctl#28]
There is currently no indication of which state of the project is being used without prior knowledge of installation or having access to the compiled source code.
A version should be tracked internally such that the binary is able to print out this information when running `envctl version`.

**Comment by juicemia** [comment]
Here's what I get when I run `envctl version`:

```
$ envctl version
2.1.0
```

Is this what you're talking about? Or are you talking about adding more details?

**Comment by loksonarius** [comment]
Oh snap, didn't see this in the printed help. Must've glossed it over. Dismiss this plis.
